Sync script

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -7,6 +7,52 @@
 
 SYNC="rsync -av --progress --delete"
 
+# Initialize flags
+DRYRUN=0
+CONFIRM=0
+OPERATION=""
+
+function usage() {
+    echo "Usage: sync [--confirm] (in|out) "
+    echo "  in : copy files from system folders"
+    echo "  out: copy files to system folders"
+    echo "  --confirm: prompt for confirmation before synchronization"
+    echo "  --dryrun: do not perform the action, just show the outcome"
+    exit $1
+}
+
+# Parse command line options, except for the last mandatory operation
+while [[ "$#" -gt 1 ]]; do
+    case "$1" in
+        --dryrun)
+            DRYRUN=1
+            ;;
+        --confirm)
+            CONFIRM=1
+            ;;
+        --help)
+            usage 0
+            ;;
+        *)
+            echo "Unknown option: $1"
+            usage 1
+            ;;
+    esac
+    shift
+done
+
+if [[ $1 == "--help" ]]; then
+    usage 0
+fi
+
+# Check if the last argument is provided and is either "in" or "out"
+if [[ "$#" -ne 1 || ( "$1" != "in" && "$1" != "out" ) ]]; then
+    echo "Error: Missing or invalid operation. Expected 'in' or 'out'."
+    usage 1
+else
+    OPERATION="$1"
+fi
+
 # Array of 'system | versioned' file couples
 common=(
     # bash
@@ -69,25 +115,6 @@ workmule=(
     "/etc/evremap.toml | evremap/evremap.toml"
 )
 
-if [[ $1 == "out" ]]; then
-    echo "Syncing OUT"
-    out=1
-elif [[ $1 == "in" ]]; then
-    echo "Syncing IN"
-    out=0
-else
-    echo "Usage: sync in|out [--confirm]"
-    echo "  in : copy files from system folders"
-    echo "  out: copy files to system folders"
-    echo "  --confirm: prompt for confirmation before synchronization"
-    exit
-fi
-
-confirm=0
-if [[ $2 == "--confirm" ]]; then
-    confirm=1
-fi
-
 function sync_files() {
     target="$1"
     echo "[$target]"
@@ -100,7 +127,7 @@ function sync_files() {
         local_file=$(echo $file | cut -d'|' -f2 | sed 's/^ *//;s/ *$//')
         local_file="$target/$local_file"
 
-        if [[ $out == 1 ]]; then
+        if [[ $OPERATION == "out" ]]; then
             in_file=$local_file
             out_file=$system_file
         else
@@ -110,7 +137,7 @@ function sync_files() {
 
         echo "* " $in_file ">" $out_file
 
-        if [[ $confirm == 1 ]]; then
+        if [[ $CONFIRM == 1 ]]; then
             printf "proceed [N/y]? "
             read confirmed
         else
@@ -119,8 +146,10 @@ function sync_files() {
 
         if [[ $confirmed == "y" ]]; then
             if [[ -f "$in_file" ]] || [[ -d "$in_file" ]]; then
-                mkdir -p $(dirname "$out_file")
-                $SYNC $in_file $out_file
+                if [[ $DRYRUN == 0 ]]; then
+                    mkdir -p $(dirname "$out_file")
+                    $SYNC $in_file $out_file
+                fi
             else
                 echo "Skipping unexistent file \"$in_file\""
             fi
